### ISSUE TITLE
[ Feature Request ] make a panel icon instead stay in plank when "continues downloads when closed" is enabled

### ISSUE THREAD

**Issue by MrMarukesu** [davidmhewitt/torrential#44]
if possible, make a wingpanel indicator for app when is closed, it makes more senses for a app in second plane instead of a icon in plank with the another's really opened apps.

**Comment by davidmhewitt** [comment]
I disagree. Having the icon in Plank makes more sense to me so that it can indicate progress in a clear manner. Both the elementary Human Interface Guidelines and the Ubuntu style guidelines advise against putting extra indicators in the tray where possible and I don't see what advantage it would give here.

**Comment by poetfreak** [comment]
except some people don't want the plank filled with icons... either. I will just stick with transmission, then.
